ULJson = [
	{
		"subUrl":"default",
		"realUrl":"./pages/mainPage.htm"
	},
	{
		"subUrl":"error",
		"realUrl":"./pages/error.htm"
	},
	{
		"subUrl":"/home/",
		"realUrl":"./pages/mainPage.htm"
	},
	{
		"subUrl":"/test1/",
		"realUrl":"./pages/subPage1.htm"
	},
	{
		"subUrl":"/test1/ViewDevDoc/",
		"realUrl":"./pages/subPage3.htm"
	},
	{
		"subUrl":"/test2/",
		"realUrl":"./pages/subPage2.htm"
	}
];